DROP VIEW IF EXISTS employee_v;  
DROP VIEW IF EXISTS contract_v;  
DROP VIEW IF EXISTS annex_v;  
DROP VIEW IF EXISTS insurance_v;  
DROP VIEW IF EXISTS departments_v;  
DROP VIEW IF EXISTS department_teams_v;  
DROP VIEW IF EXISTS article62_v;  
DROP VIEW IF EXISTS declaration1_v;  
DROP VIEW IF EXISTS declaration6_v;  
